[holomapping]
holosource = "=>emergence-skeleton"
files = [
    "**",

    # superceded by skeleton-v2 at event-handlers/Emergence/People/RegistrationRequestHandler
    "!event-handlers/RegistrationRequestHandler/**",
]
