name: Projections

on:
  push:
    tags:
      - 'v2.*'
  schedule:
    - cron: '0 * * * *'


jobs:
  holobranch-projections:
    runs-on: ubuntu-latest
    steps:
    - name: Update emergence/skeleton/v2 holobranch
      uses: JarvusInnovations/hologit@actions/projector/v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        HAB_LICENSE: accept
      with:
        ref: releases/v2
        holobranch: emergence-skeleton
        commit-to: emergence/skeleton/v2
    - name: Update emergence/vfs-site/v2 holobranch
      uses: JarvusInnovations/hologit@actions/projector/v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        HAB_LICENSE: accept
      with:
        ref: releases/v2
        holobranch: emergence-vfs-site
        commit-to: emergence/vfs-site/v2
